### ISSUE TITLE
Should we add the vignettes as appendices? should we add the code of figure 3 as a vignette? 

### ISSUE THREAD

**Issue by fmichonneau** [fmichonneau/rotl-ms#13]
My initial thinking for adding the code of figure 3 (GBIF map) as an appendix was that:
- the code is relatively simple and will probably still work for the next few years
- I thought it was important to make the manuscript reproducible, and be consistent with the other figures for which we include the code to generate them in the manuscript
- the code seems too long to be added in the text

This example seems a little too short to be in its own vignette. Alternatively, we could add it to the `data-mashup` vignette.

Regarding whether we should include the current vignettes as appendices of the manuscript, I'm slightly against it as there is a good chance that they are going to be out-of-date soon as the API changes.

What are your thoughts on this?

**Comment by dwinter** [comment]
I tend to agree, I think we can address the reviewer's comment by making a more explicit summary (and link) of the vignettes and noting they will be maintained through changes to Open Tree?

**Comment by fmichonneau** [comment]
That sounds good. I'm going to add this, and clarify the last paragraph of the manuscript.

**Comment by fmichonneau** [comment]
I'm thinking we can also ask the editors if they think that the code for Figure 3 is too long to be included in the manuscript instead of making it an appendix.
