### ISSUE TITLE
Wait until v3 of the api?

### ISSUE THREAD

**Issue by dwinter** [fmichonneau/rotl-ms#14]
With a new version of the API on the way (ropensci/rotl#64) , is it possible that our manuscript will be out of date by the time it get's published? 

I can take some time to check how many of the examples in the MS are effected by changes, but if v3 is not far away it might make sense to wait a little while (much as I'd like to get the revision straight back). 

@kcranston is there an e.t.a for when this change might happen?

**Comment by kcranston** [comment]
v3 will be out by end of March (sorry about the bad timing!). The spec will be finalized by end of day tomorrow (March 11). That process is ongoing in [this doc](https://docs.google.com/document/d/1XcgoQGJVxSgk-yKB-NAayQNZ2_QUQuw9_RIvbR2LeTw/edit#) which will be transferred to [these wiki pages](https://github.com/OpenTreeOfLife/germinator/wiki/Open-Tree-of-Life-Web-APIs) next week. 

Let me know how I can help!

**Comment by fmichonneau** [comment]
I thought about this too...

The main goal of the manuscript is to present the package and have something people who use it may want to cite. We don't include too many functions in the manuscript itself, and the ones we include will still be valid even if the API gets updated.

From the doc Karen sent, it seems most changes concern the naming of the elements being returned by the API, so it won't be visible to the users for the most part.

I think we should go ahead with resubmitting the manuscript, and if anything breaks (which seems unlikely), we will have time to correct at the proof stage.

What do you think @dwinter @josephwb ?

**Comment by dwinter** [comment]
Having gone through this in a little more detail, I think there shuld only be a handful of changes required.

We should perhaps include a note in the cover letter or reply document mentioning some small tweaks my be needed though?

**Comment by josephwb** [comment]
Closing this, since we decided in favour of it (in fact it is almost done).
