### ISSUE TITLE
Remove graph of life paragraph?

### ISSUE THREAD

**Issue by dwinter** [fmichonneau/rotl-ms#15]
The graph of life endpoints are being discontinued in future releases, and, as far as I can tell, where never intended for end-users. 

Currently we mention there existance:

> Additionally, the project provides access to other data, the Graph of Life, that
> stores information about the underlying tree alignment graph \citep{Smith2013}
> used to synthesize the various sources of information from which the Open Tree
> is assembled. Data from this API are not intended for normal users, and its
> use will not be demonstrated in this paper, although \texttt{rotl} has functions to
> retrieve data it provides

Should we just delete this entirely?
.

**Comment by fmichonneau** [comment]
I agree, I'm removing it. I'm also going to add a mention to the collection endpoint that is not currently implemented (but that will be once enough documentation is available to do so, see ropensci/rotl#60)
