### ISSUE TITLE
Missing data(cats) in appendix code?

### ISSUE THREAD

**Issue by josephwb** [fmichonneau/rotl-ms#5]
@dwinter I cannot execute:

``` R
cat_species <- cat_tree$tip.label
```

because `cat_tree` has not been imported. I do not see this as part of the repo. Is it supposed to come from `rotl`, or some other package, or downloaded from OToL?

**Comment by dwinter** [comment]
Hi @josephwb, I think this is relying on the `cat_tree` that we download from OToL in the manuscript to be present in the R session. 

I'll make a bug-fix branch to make the appendix a stand-alone reproducible example, and then you can see if that branch can be merged with your edits  (it may just be easier to copy the fix, which will likely be a couple of lines).

**Comment by josephwb** [comment]
Ok, thanks. It wasn't clear to me if this was going to be a canned example (i.e. grab with`data(cat_tree);`

**Comment by dwinter** [comment]
The fix is in :smile: With this I can paste in the appendix code the map, let me know if there are still problems.

**Comment by josephwb** [comment]
Great, thanks. I'll just paste it into my edits.
