### ISSUE TITLE
Washed out figure legend

### ISSUE THREAD

**Issue by dwinter** [fmichonneau/rotl-ms#6]
Using `alpha=0.3` to blend over-plotted points in the `cat_map` figure makes the legend hard to read. Google and [stackoverflow](http://stackoverflow.com/questions/5290003/how-to-set-legend-alpha-with-ggplot2) tell me there is a fix for this. We can add this extra function call to the plot:

``` r
+ guides(colour = guide_legend(override.aes = list(alpha = 1)))
```

I think it's worth doing, but also wanted to check with both of you about this. The only reason to hold off is that the appendix already contains some fairly obscure tricks to format and plot the data. Is another obscure-looking R command going to make this look inaccessible to folks just learning the language?

**Comment by fmichonneau** [comment]
maybe we can change the background color in the legend to match the dark gray used to draw the continents?

**Comment by fmichonneau** [comment]
I tried a few things, and I think reducing the size of the points while getting rid off the transparency is good compromise in aesthetics of the map/code simplicity. I did however change the background of the legend so it matches the color of the continents.
